source .bash_profile

sqlplus -s /nolog <<EOF
connect cmdb/cmdb
SELECT 
(SELECT COUNT(*) FROM CM_TENANT) AS TENANTs,
(SELECT COUNT(*) FROM CM_VIMZONE) AS VIMs,
(SELECT COUNT(*) FROM CM_VDC) AS VDCs,
(SELECT COUNT(*) FROM CM_VAPP) AS VAPPs,
(SELECT COUNT(*) FROM CM_VN) AS VNs,
(SELECT COUNT(*) FROM CM_SUBNET) AS SUBNETs,
(SELECT COUNT(*) FROM CM_SERVER) AS VMs,
(SELECT COUNT(*) FROM CM_VNIC) AS VM_VNICs,
(SELECT COUNT(*) FROM CM_BSV) AS BSVs
FROM DUAL;
EOF
